import { Inter } from "next/font/google";
import "../globals.scss";

import Header from "./Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
	return (
		<html lang="en">
			<head>
				<link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;600&display=swap" rel="stylesheet"/>
			</head>
			<body className={inter.className}>
				<Header/>
				{children}
			</body>
		</html>
	);
}
