import "app/globals.scss";

import Header from "components/Header";
import TopMenu from "components/TopMenu";
import TableSpace from "components/TableSpace";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head></head>
      <body>
        <Header />
        <TopMenu />
        <TableSpace>{children}</TableSpace>
      </body>
    </html>
  );
}
